kind: Service
apiVersion: v1
metadata:
  name: webdasar-service
 # namespace: production
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: webdasar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdasar-deployment
 # namespace: production
spec:
  selector:
    matchLabels:
      app: webdasar
  replicas: 1
  template:
    metadata:
      labels:
        app: webdasar
    spec:
      containers:
      - name: landing
        image: 25092018/webdasar
        ports:
        - containerPort: 80
---
kind: HorizontalPodAutoscaler 
apiVersion: autoscaling/v2beta1 
metadata: 
  name: webdasar 
spec: 
  maxReplicas: 10 
  minReplicas: 1 
  scaleTargetRef: 
    apiVersion: app/v1 
    kind: Deployment 
    name: webdasar-deployment 
  metrics: 
  - type: Resource 
    resource: 
      name: cpu 
      target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: landing-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: untukcodemi.rizdin.online
    http:
      paths:
      #- path: /
      - backend:
          serviceName: webdasar-service
          servicePort: 80
